apiVersion: v1
kind: Service
metadata:
  name: {{ include "whiteapp.fullname" . }}
  labels:
    {{- include "whiteapp.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "whiteapp.selectorLabels" . | nindent 4 }}

