# assignment-apps/charts/red-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redapp.fullname" . }}
  labels:
    {{- include "redapp.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    {{- include "redapp.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

